version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres_coffee
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: coffee
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: